name: Build others
on:
  workflow_dispatch:

jobs:
  build-macos-x86_64:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: gh_pm44
      - name: Install Dependencies
        run: |
          brew install make automake bison
          brew install libxaw gcc
          # compile_macos_gcc.sh expects this path.  Kludge it.
          sudo mkdir -p /opt/X11/include
          sudo ln -s /usr/local/include/freetype2 /opt/X11/include/freetype2
      - name: Build X86_64
        run: |
          PATH='/usr/local/opt/bison/bin:'$PATH
          ./compile_macos_gcc.sh || true # Will fail to install
          if [ ! -f release/src/ngspice ]; then false; fi
      - name: Install X86_64
        run: |
          cd release
          sudo make install
          cd ..
          mkdir build
          for i in bin lib share ; do
            mkdir -p build/$i
            cp -r /usr/local/$i/ngspice build/$i/
          done
          echo Create README.ngspice
          echo 'This binary package of ngspice was built at https://github.com/gatk555/ngspice.' > build/README.ngspice
          echo 'The source code came from the pre-master-44 branch.' > build/README.ngspice
          echo 'Install to /usr/local.' > build/README.ngspice
      - name: Save X86_64
        uses: actions/upload-artifact@v4
        with:
          name: Ngspice pre-master-44, Macos X86_64
          path: build
      - name: Clean
        run: |
          rm -rf release build
          for i in bin lib share ; do
            sudo rm -rf /usr/local/$i/ngspice
          done
