name: Build a test branch
on:
  workflow_dispatch:

jobs:
  build-win-X64:
    runs-on: windows-latest
    steps:
      - name: Flex and Bison
        run: |
          md ..\flex-bison
          cd ..\flex-bison
          curl.exe -L -O "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
          unzip win_flex_bison-2.5.25
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: gh_pm44
      - uses: microsoft/setup-msbuild@v2
      - name: Build
        shell: cmd
        run: |
          set config=Release
          set plat=x64
          set suffix=64
          set opt=-property:Configuration=%config% -property:Platform=%plat%
          msbuild %opt% visualc\xspice\cmpp\cmpp.vcxproj
          msbuild %opt% visualc\xspice\cmpp\cmpp.vcxproj
          msbuild %opt% visualc\xspice\analog.vcxproj
          msbuild %opt% visualc\xspice\digital.vcxproj
          msbuild %opt% visualc\xspice\spice2poly.vcxproj
          msbuild %opt% visualc\xspice\table.vcxproj
          msbuild %opt% visualc\xspice\xtradev.vcxproj
          msbuild %opt% visualc\xspice\xtraevt.vcxproj
          set cms=codemodels\%plat%\%config%
          md visualc\%cms%
          move visualc\xspice\%cms%\*.cm visualc\%cms%
          msbuild %opt% visualc\KLU/KLU_COMPLEX.vcxproj
          msbuild %opt% visualc\sharedspice.vcxproj
          cd visualc
          dir /s *.dll
          dir /s  C:\Spice64
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Ngspice pre-master-44, Windows X86-64 console only
          path: C:\Spice64
