name: Build a test branch
on:
  workflow_dispatch:

jobs:
  build-win-X64:
    runs-on: windows-latest
    steps:
      - name: Flex and Bison
        run: |
          md ..\flex-bison
          cd ..\flex-bison
          curl.exe -L -O "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
          unzip win_flex_bison-2.5.25
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: gh_pm44
      - uses: microsoft/setup-msbuild@v2
      - name: Build
        shell: cmd
        run: |
          set config=Release
          set plat=x64
          set suffix=64
          set opt=-property:Configuration=%config% -property:Platform=%plat%
          msbuild %opt% visualc\xspice\cmpp\cmpp.vcxproj
          msbuild %opt% visualc\xspice\cmpp\cmpp.vcxproj
          msbuild %opt% visualc\xspice\analog.vcxproj
          msbuild %opt% visualc\xspice\digital.vcxproj
          msbuild %opt% visualc\xspice\spice2poly.vcxproj
          msbuild %opt% visualc\xspice\table.vcxproj
          msbuild %opt% visualc\xspice\xtradev.vcxproj
          msbuild %opt% visualc\xspice\xtraevt.vcxproj
          set cms=codemodels\%plat%\%config%
          md visualc\%cms%
          move visualc\xspice\%cms%\*.cm visualc\%cms%
          msbuild %opt% visualc\KLU/KLU_COMPLEX.vcxproj
          msbuild %opt% visualc\vngspice.vcxproj
          msbuild %opt% visualc\sharedspice.vcxproj
          set config=console_release
          set opt=-property:Configuration=%config% -property:Platform=%plat%
          msbuild %opt% visualc\vngspice.vcxproj
          copy visualc\vngspice\Release.x64\ngspice.exe C:\Spice64\bin\gui.exe
          md c:\Spice64\bin-dll
          copy visualc\sharedspice\Release.x64\ngspice.dll c:\Spice64\bin-dll
          copy visualc\sharedspice\Release.x64\ngspice.exp c:\Spice64\bin-dll
          copy visualc\sharedspice\Release.x64\ngspice.lib c:\Spice64\bin-dll
          c:
          cd \Spice64
          move bin\ngspice.exe bin\ngspice_con.exe
          move bin\gui.exe bin\ngspice.exe
          echo Create README.ngspice
          echo This binary build of ngspice was built at https://github.com/gatk555/ngspice. > README.ngspice
          echo The source code came from the pre-master-44 branch. >> README.ngspice
          echo Install to C:\Spice64\. >> README.ngspice
      - uses: actions/checkout@v4
        with:
          repository: gatk555/test
      - name: Add DLL
        shell: cmd
        run: |
          unzip libomp.zip
          copy libomp140.x86_64.dll C:\Spice64\bin\vcomp140.dll
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Ngspice pre-master-44, Windows X86-64
          path: C:\Spice64
